Task/add missing task docs
tandemdude/hikari-lightbulb pull request #484
Opened 2024-11-05 17:11 UTC by syncblaze

### Summary
Added missing documentation for the task class and decorators 

### Checklist

- [ ] I have run `nox` and all the pipelines have passed.

- [ ] I have created a changelog fragment to describe this change

### Related issues

2024-11-05 18:46 UTC, parafoxia requested changes
Wording looks fine, I would just say the changes need to be in British English to match the rest of the docs (i.e. behavior -> behaviour, canceled -> cancelled).

2024-11-06 08:45 UTC, null-domain approved these changes
LGTM, just a few nitpicks about wordiness and clarity :)

2024-11-06 08:45 UTC, null-domain commented on fragments/484.documentation.md
> +Added missing Documentation for the `Task` class and secondary `task` decorators, stating that setting `max_failures` or `max_invocations` to a negative number will disable that behaviour.
This could be made shorter -
```suggestion
Document the behaviour of `max_failures` and `max_invocations` in tasks and how to disable each.
```

2024-11-06 08:45 UTC, null-domain commented on lightbulb/client.py
> +                no matter how often the task fails.
```suggestion
                Setting this to a negative number will prevent the task from being cancelled, regardless of
                how often the task fails.
```

2024-11-06 08:45 UTC, null-domain commented on lightbulb/loaders.py
> +                no matter how often the task fails.
```suggestion
                Setting this to a negative number will prevent the task from being cancelled, regardless of
                how often the task fails.
```

2024-11-06 08:45 UTC, null-domain commented on lightbulb/tasks.py
> +            no matter how often the task fails.
```suggestion
            Setting this to a negative number will prevent the task from being cancelled, regardless of
            how often the task fails.
```

2024-11-06 09:25 UTC, merged